[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "python3 -m pip install -r server/requirements.txt",
  "npm install --prefix client"
]

[phases.build]
cmds = ["npm run build --prefix client"]

[start]
cmd = "uvicorn server.main:app --host 0.0.0.0 --port $PORT"
